In [8]:
import pandas as pd

In [9]:
df1 = pd.read_csv("overlapping_asm_results.csv")
df2 = pd.read_csv("overlapping_asm_results_9.csv")
df3 = pd.read_csv("overlapping_asm_results_MM3.csv")
df = pd.concat([df1, df2, df3])
df

,n,N,NN,overlap_n,residual norm,iterations,condition number,estimate,ratio
0,16,16,16,0,0.000016,32,20.561306,1.0,20.561306
1,32,16,16,0,0.000032,42,36.082878,2.0,18.041439
2,32,16,16,1,0.000037,35,35.840557,2.0,17.920279
3,32,32,16,0,0.000038,41,34.612089,4.0,8.653022
4,32,32,32,0,0.000044,32,21.157236,1.0,21.157236
...,...,...,...,...,...,...,...,...,...
79,512,128,8,1,0.000593,250,1908.834317,1024.0,1.864096
80,512,128,8,2,0.000656,245,1653.795173,512.0,3.230069
81,512,256,8,0,0.000712,506,7473.507025,2048.0,3.649173
82,512,256,8,1,0.000707,291,2421.330325,2048.0,1.182290
83,512,512,8,0,0.000719,688,13243.622605,4096.0,3.233306

In [10]:
def get_order(row):
    h = 1 / row["n"]
    H = 1 / row["N"]
    HH = 1 / row["NN"]
    delta = row["overlap_n"] / row["n"]
    return HH * HH / H / max(h, delta)

df["estimate"] = df.apply(get_order, axis=1)
df["ratio"] = df["condition number"] / df["estimate"]

In [11]:
df[(df.N == df.NN) & (df.n == 512)].pivot_table(values="condition number", index="N", columns="overlap_n")

overlap_n,0,1,2,4,8,16,32
N,,,,,,,
8,1104.161760,754.054049,513.355308,313.854111,175.544648,90.376074,46.962473
16,567.651364,579.421427,491.133962,375.278623,247.527208,151.232673,NaN
32,286.632636,325.972966,320.086036,289.495750,264.153369,NaN,NaN
64,143.797114,170.169462,172.153993,189.155206,NaN,NaN,NaN
128,71.871883,87.679504,100.852409,NaN,NaN,NaN,NaN
256,36.175398,49.417384,NaN,NaN,NaN,NaN,NaN
512,22.603224,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
df[(df.N == df.NN) & (df.n == 512)].pivot_table(values="iterations", index="N", columns="overlap_n")

overlap_n     0      1      2     4     8     16    32
N
8          193.0  126.0   99.0  76.0  55.0  39.0  31.0
16         145.0  132.0  114.0  88.0  70.0  54.0   NaN
32         110.0  113.0  106.0  95.0  87.0   NaN   NaN
64          79.0   82.0   82.0  89.0   NaN   NaN   NaN
128         57.0   61.0   67.0   NaN   NaN   NaN   NaN
256         42.0   48.0    NaN   NaN   NaN   NaN   NaN
512         34.0    NaN    NaN   NaN   NaN   NaN   NaN

In [16]:
df[(df.NN == 16) & (df.n == 512)].pivot_table(values="condition number", index="N", columns="overlap_n")

overlap_n,0,1,2,4,8,16
N,,,,,,
16,567.651364,579.421427,491.133962,375.278623,247.527208,151.232673
32,616.854032,652.209708,589.694303,489.383183,387.165428,NaN
64,834.413222,728.104880,579.340340,653.307728,NaN,NaN
128,1255.090918,797.820023,823.974496,NaN,NaN,NaN
256,2007.201426,1005.332206,NaN,NaN,NaN,NaN
512,3457.172117,NaN,NaN,NaN,NaN,NaN

In [17]:
df[(df.NN == 8) & (df.n == 512)].pivot_table(values="condition number", index="N", columns="overlap_n")

overlap_n,0,1,2,4,8,16,32
N,,,,,,,
8,1104.161760,754.054049,513.355308,313.854111,175.544648,90.376074,46.962473
16,1213.977652,1003.230048,760.277231,511.388680,299.529562,166.325919,NaN
32,1662.907791,1250.410586,1028.025934,751.192398,505.169044,NaN,NaN
64,2595.115257,1542.136030,1276.339829,1081.639358,NaN,NaN,NaN
128,4194.948209,1908.834317,1653.795173,NaN,NaN,NaN,NaN
256,7473.507025,2421.330325,NaN,NaN,NaN,NaN,NaN
512,13243.622605,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# GMRES?
# multiplikatywnie (kolorowanie)?
# czy warto w teorię?
# Neumann-Neumann?
# Spojrzeć na https://drive.google.com/drive/u/2/folders/1x0mXSbO1OSXAdE9AR1jE-mJWURbmpuUv dobre wyniki?
# co jest dla nieciągłego współczynnika z overlapem?