In [2]:
import pandas as pd

In [3]:
df1 = pd.read_csv("overlapping_asm_results.csv")
df2 = pd.read_csv("overlapping_asm_results_9.csv")
df = pd.concat([df1, df2])
df

,n,N,NN,overlap_n,residual norm,iterations,condition number,estimate,ratio
0,16,16,16,0,0.000016,32,20.561306,1.0,20.561306
1,32,16,16,0,0.000032,42,36.082878,2.0,18.041439
2,32,16,16,1,0.000037,35,35.840557,2.0,17.920279
3,32,32,16,0,0.000038,41,34.612089,4.0,8.653022
4,32,32,32,0,0.000044,32,21.157236,1.0,21.157236
...,...,...,...,...,...,...,...,...,...
51,512,512,32,0,0.000682,199,931.903190,256.0,3.640247
52,512,512,64,0,0.000712,111,271.953087,64.0,4.249267
53,512,512,128,0,0.000699,65,88.171145,16.0,5.510697
54,512,512,256,0,0.000642,42,34.968848,4.0,8.742212
55,512,512,512,0,0.000611,34,22.603224,1.0,22.603224

In [41]:
def get_order(row):
    h = 1 / row["n"]
    H = 1 / row["N"]
    HH = 1 / row["NN"]
    delta = row["overlap_n"] / row["n"]
    return HH * HH / H / max(h, delta)

df["estimate"] = df.apply(get_order, axis=1)
df["ratio"] = df["condition number"] / df["estimate"]
df[(df.N == df.NN) & (df.n == 512)].pivot_table(values="condition number", index="N", columns="overlap_n")

overlap_n,0,1,2,4,8,16
N,,,,,,
16,567.651364,579.421427,491.133962,375.278623,247.527208,151.232673
32,286.632636,325.972966,320.086036,289.495750,264.153369,NaN
64,143.797114,170.169462,172.153993,189.155206,NaN,NaN
128,71.871883,87.679504,100.852409,NaN,NaN,NaN
256,36.175398,49.417384,NaN,NaN,NaN,NaN
512,22.603224,NaN,NaN,NaN,NaN,NaN