In [ ]:
from experiments import UniformMeshes, discretize, continuous_coefficient_2d
import numpy as np
import pandas as pd
import torch
import os
import json
import pyamgx
import tqdm

AMGX version 2.5.0
Built on Jul  5 2025, 09:37:04
Compiled with CUDA Runtime 12.6, using CUDA driver 12.7
The AMGX_initialize_plugins API call is deprecated and can be safely removed.

In [ ]:
mesh_family = UniformMeshes(d=2, m=11)

In [ ]:
def test_config(cfg, problem, rep_setup=3, rep_solve=5):
    rsc = pyamgx.Resources().create_simple(cfg)

    A = pyamgx.Matrix().create(rsc)
    b = pyamgx.Vector().create(rsc)
    x = pyamgx.Vector().create(rsc)

    A.upload_CSR(problem.exact_form_matrix)
    b.upload(problem.load_vector)

    solver = pyamgx.Solver().create(rsc, cfg)

    setup_times = []
    for _ in range(rep_setup):
        start = torch.cuda.Event(enable_timing=True)
        end = torch.cuda.Event(enable_timing=True)

        start.record()
        solver.setup(A)
        end.record()
        torch.cuda.synchronize()
        setup_times.append(start.elapsed_time(end) / 1000)

    solve_times = []
    for _ in range(rep_solve):
        start = torch.cuda.Event(enable_timing=True)
        end = torch.cuda.Event(enable_timing=True)

        x.set_zero(n=problem.load_vector.shape[0], block_dim=1)
        start.record()
        solver.solve(b, x, zero_initial_guess=True)
        end.record()
        torch.cuda.synchronize()
        solve_times.append(start.elapsed_time(end) / 1000)

    x_vec = np.zeros_like(problem.load_vector)
    x.download(x_vec)
    residual = np.linalg.norm(problem.exact_form_matrix @ x_vec - problem.load_vector)

    A.destroy()
    b.destroy()
    x.destroy()
    solver.destroy()
    rsc.destroy()

    return {
        "setup_time": min(setup_times),
        "solve_time": min(solve_times),
        "residual": residual,
    }

In [5]:
def patch_config(cfg):
    cfg = cfg.copy()
    cfg["solver"]["print_grid_stats"] = 0
    cfg["solver"]["print_solve_stats"] = 0
    cfg["solver"]["obtain_timings"] = 0
    cfg["solver"]["convergence"] = "RELATIVE_INI"
    cfg["solver"]["tolerance"] = 1e-9
    cfg["solver"]["max_iters"] = 1000
    if "preconditioner" in cfg:
        cfg["preconditioner"]["print_grid_stats"] = 0
        cfg["preconditioner"]["print_solve_stats"] = 0
    if "preconditioner" in cfg["solver"]:
        cfg["solver"]["preconditioner"]["print_grid_stats"] = 0
        cfg["solver"]["preconditioner"]["print_solve_stats"] = 0
    return cfg

In [6]:
configs = {}
for filename in tqdm.tqdm(os.listdir("/workspace/AMGX/src/configs/")):
    if filename.endswith(".json"):
        with open(f"/workspace/AMGX/src/configs/{filename}") as f:
            cfg_json = patch_config(json.load(f))
            name = filename[:-5]
            if "GMRES" in cfg_json["solver"]["solver"]:
                cfg_json["solver"]["solver"] = "PCG"
                name += "__MOD_PCG"
            configs[name] = cfg_json

100%|██████████| 63/63 [00:00<00:00, 39753.45it/s]

In [ ]:
double_precision_discrete_problem = discretize(
    continuous_coefficient_2d.problem, mesh_family["S6"]
)

In [8]:
results = []
for name, cfg_json in tqdm.tqdm(configs.items()):
    cfg = pyamgx.Config().create_from_dict(cfg_json)
    results.append(
        {
            **test_config(
                cfg, double_precision_discrete_problem, rep_setup=1, rep_solve=1
            ),
            "config": name,
        }
    )
    cfg.destroy()

df = pd.DataFrame(results)

 94%|█████████▎| 58/62 [01:38<00:03,  1.31it/s]!!! detected some memory leaks in the code: trying to free non-empty temporary device pool !!!
ptr:     0x7049603f2000 size: 4096
100%|██████████| 62/62 [01:40<00:00,  1.61s/it]

In [9]:
df

    setup_time  solve_time      residual                    config
0     0.032836    1.616566           NaN          AGGREGATION_DILU
1     0.008345    0.115541  2.327248e-09            AGGREGATION_GS
2     0.007158    0.382625           NaN        AGGREGATION_JACOBI
3     0.005700    0.380574           NaN    AGGREGATION_LOW_DEG_BJ
4     0.015085    1.577244           NaN  AGGREGATION_LOW_DEG_DILU
..         ...         ...           ...                       ...
57    0.012560    0.024951  1.488632e-09          V-cheby-smoother
58    0.009000    0.031024  1.681975e-09     V-cheby_poly-smoother
59    0.006329    0.257683           NaN                         V
60    0.006300    0.751502           NaN                         W
61    0.006513    0.031192  1.521604e-09                 agg_cheb4

[62 rows x 4 columns]

In [10]:
working_configs = list(df[df.residual < 1e-7]["config"])
len(working_configs)

24

In [ ]:
double_precision_discrete_problem = discretize(
    continuous_coefficient_2d.problem, mesh_family["S8"]
)

In [12]:
results = []
for name in tqdm.tqdm(working_configs):
    cfg_json = configs[name]
    cfg = pyamgx.Config().create_from_dict(cfg_json)
    results.append(
        {
            "config": name,
            **test_config(
                cfg, double_precision_discrete_problem, rep_setup=1, rep_solve=3
            ),
        }
    )

df2 = pd.DataFrame(results)

 92%|█████████▏| 22/24 [00:31<00:01,  1.15it/s]!!! detected some memory leaks in the code: trying to free non-empty temporary device pool !!!
ptr:     0x704963eee000 size: 4096
100%|██████████| 24/24 [00:33<00:00,  1.38s/it]

In [13]:
stats8 = df2.pivot_table(
    index="config", values=["setup_time", "solve_time", "residual"], aggfunc="min"
)
stats8

,residual,setup_time,solve_time
config,,,
AGGREGATION_GS,5.644006e-10,0.019432,1.651236
AGGREGATION_LOW_DEG_GS,5.644006e-10,0.019371,1.648889
AGGREGATION_THRUST_GS,5.061256e-10,0.017188,1.625500
AMG_AGGRREGATION_CG,3.949181e-10,0.010044,1.010899
AMG_CLASSICAL_AGGRESSIVE_CHEB_L1_TRUNC,1.890851e-10,0.023512,0.042038
AMG_CLASSICAL_AGGRESSIVE_L1_TRUNC__MOD_PCG,2.357284e-10,0.022959,0.029187
AMG_CLASSICAL_AGGRESSIVE_L1__MOD_PCG,3.166038e-10,0.021494,0.028077
AMG_CLASSICAL_L1_AGGRESSIVE_HMIS__MOD_PCG,3.683359e-10,0.626351,0.023626
AMG_CLASSICAL_L1_TRUNC__MOD_PCG,2.461969e-10,0.028935,0.025771
AMG_CLASSICAL_PMIS__MOD_PCG,2.357284e-10,0.022841,0.029182
CG_DILU,5.685075e-05,0.000068,0.141846
FGMRES_CLASSICAL_AGGRESSIVE_HMIS__MOD_PCG,2.394614e-10,0.624253,0.023060
FGMRES_CLASSICAL_AGGRESSIVE_PMIS__MOD_PCG,2.357284e-10,0.022831,0.029158
FGMRES_NOPREC__MOD_PCG,5.685075e-05,0.000079,0.150283
GMRES_AMG_D2__MOD_PCG,2.566997e-10,0.018945,0.027970
GMRES__MOD_PCG,5.685075e-05,0.000081,0.150222
PBICGSTAB_NOPREC,4.291284e-07,0.000121,0.316382
PCG_AGGREGATION_JACOBI,3.882550e-07,0.016440,1.326692
PCG_NOPREC,5.685075e-05,0.000079,0.150149
V-cheby-aggres-L1-trunc,3.900959e-10,0.017466,0.158224
V-cheby-aggres-L1-trunc-userLambda,3.940014e-10,0.017620,0.150262
V-cheby-smoother,2.916896e-10,0.021939,0.106553
V-cheby_poly-smoother,4.049089e-10,0.026689,0.111717
agg_cheb4,3.552045e-10,0.009949,0.172493

In [14]:
fast_solvers = list(
    stats8[
        (stats8.solve_time < 2 * stats8.solve_time.min()) & (stats8.residual < 1e-06)
    ].index
)
fast_solvers

['AMG_CLASSICAL_AGGRESSIVE_CHEB_L1_TRUNC',
 'AMG_CLASSICAL_AGGRESSIVE_L1_TRUNC__MOD_PCG',
 'AMG_CLASSICAL_AGGRESSIVE_L1__MOD_PCG',
 'AMG_CLASSICAL_L1_AGGRESSIVE_HMIS__MOD_PCG',
 'AMG_CLASSICAL_L1_TRUNC__MOD_PCG',
 'AMG_CLASSICAL_PMIS__MOD_PCG',
 'FGMRES_CLASSICAL_AGGRESSIVE_HMIS__MOD_PCG',
 'FGMRES_CLASSICAL_AGGRESSIVE_PMIS__MOD_PCG',
 'GMRES_AMG_D2__MOD_PCG']

In [15]:
# HMIS Thrust errors for large problems
fast_solvers = [solver for solver in fast_solvers if not "HMIS" in solver]
fast_solvers

['AMG_CLASSICAL_AGGRESSIVE_CHEB_L1_TRUNC',
 'AMG_CLASSICAL_AGGRESSIVE_L1_TRUNC__MOD_PCG',
 'AMG_CLASSICAL_AGGRESSIVE_L1__MOD_PCG',
 'AMG_CLASSICAL_L1_TRUNC__MOD_PCG',
 'AMG_CLASSICAL_PMIS__MOD_PCG',
 'FGMRES_CLASSICAL_AGGRESSIVE_PMIS__MOD_PCG',
 'GMRES_AMG_D2__MOD_PCG']

In [ ]:
double_precision_discrete_problem = discretize(
    continuous_coefficient_2d.problem, mesh_family["S11"]
)

In [20]:
results = []
for config in tqdm.tqdm(fast_solvers):
    cfg_json = configs[config]
    cfg = pyamgx.Config().create_from_dict(cfg_json)
    results.append(
        {
            "config": config,
            **test_config(
                cfg, double_precision_discrete_problem, rep_setup=3, rep_solve=30
            ),
        }
    )

df3 = pd.DataFrame(results)

100%|██████████| 7/7 [03:57<00:00, 33.87s/it]

In [21]:
stats11 = df3.pivot_table(
    index="config", values=["setup_time", "solve_time", "residual"], aggfunc="min"
)
stats11

,residual,setup_time,solve_time
config,,,
AMG_CLASSICAL_AGGRESSIVE_CHEB_L1_TRUNC,3.314635e-11,0.785086,1.297546
AMG_CLASSICAL_AGGRESSIVE_L1_TRUNC__MOD_PCG,5.236861e-11,0.788167,0.973072
AMG_CLASSICAL_AGGRESSIVE_L1__MOD_PCG,4.163931e-11,0.776810,0.858110
AMG_CLASSICAL_L1_TRUNC__MOD_PCG,3.817696e-11,1.134446,0.859928
AMG_CLASSICAL_PMIS__MOD_PCG,4.404525e-11,0.784341,0.972779
FGMRES_CLASSICAL_AGGRESSIVE_PMIS__MOD_PCG,4.404525e-11,0.784328,0.973032
GMRES_AMG_D2__MOD_PCG,5.368200e-11,0.533248,1.028181

In [22]:
stats11.sort_values("solve_time")

,residual,setup_time,solve_time
config,,,
AMG_CLASSICAL_AGGRESSIVE_L1__MOD_PCG,4.163931e-11,0.776810,0.858110
AMG_CLASSICAL_L1_TRUNC__MOD_PCG,3.817696e-11,1.134446,0.859928
AMG_CLASSICAL_PMIS__MOD_PCG,4.404525e-11,0.784341,0.972779
FGMRES_CLASSICAL_AGGRESSIVE_PMIS__MOD_PCG,4.404525e-11,0.784328,0.973032
AMG_CLASSICAL_AGGRESSIVE_L1_TRUNC__MOD_PCG,5.236861e-11,0.788167,0.973072
GMRES_AMG_D2__MOD_PCG,5.368200e-11,0.533248,1.028181
AMG_CLASSICAL_AGGRESSIVE_CHEB_L1_TRUNC,3.314635e-11,0.785086,1.297546

In [ ]:
stats11.to_csv("../results/amgx_selection_2d.csv")